export const ON_SELECT_TAB = "ON_SELECT_TAB";

export const MOVIE_REQUEST_LOADING = "MOVIE_REQUEST_LOADING";
export const MOVIE_REQUEST_SUCCESS = "MOVIE_REQUEST_SUCCESS";
export const MOVIE_REQUEST_FAIL = "MOVIE_REQUEST_FAIL";
